// This file is generated by GoAdmin CLI adm.
package main

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "env" => http://localhost:9033/admin/info/env
// "parameters" => http://localhost:9033/admin/info/parameters
//
// example end
var Generators = map[string]table.Generator{

	"env":        GetEnvTable,
	"parameters": GetParametersTable,
	// generators end
}
